#! /bin/sh 

#######################################################################
#
# Check install condtion 
#
if  [ `id -u` -ne 0 ] ; then
  # Only root can run this. 
  echo "ERROR : Please run as root. ex: sudo ./install_without_vscode"
  exit 1
fi

# Update repository before installing. 
apt-get -y update

# Install essential tools to use RaspberryPi SDK. 
apt-get -y install build-essential cmake ninja-build git doxygen

# Install arm cross development tool chain
apt-get -y install gcc-arm-none-eabi libnewlib-arm-none-eabi

